export const TEX_MAGIC_PROGRAM_NAME = 'TEX_MAGIC_PROGRAM_NAME'
export const BIB_MAGIC_PROGRAM_NAME = 'BIB_MAGIC_PROGRAM_NAME'
export const MAGIC_PROGRAM_ARGS_SUFFIX = '_WITH_ARGS'
export const MAX_PRINT_LINE = '10000'
